plugins {
    id 'kazuki.kotlin-conventions-junit4'
    alias(libs.plugins.ksp)
    id 'com.anaplan.engineering.kazuki-generation'
}

dependencies {
    api project(":kazuki-core")
    ksp project(":kazuki-ksp")
}

// TODO - figure out how to do this from the plugin ?!
sourceSets {
    test {
        kotlin {
            srcDir(generateRecordTests)
        }
    }
}

ksp {
    arg("com.anaplan.engineering.kazuki.compile.debug.level", "INFO")
    useKsp2 = false
}

test {
    enableAssertions = true
}