plugins {
    id 'kazuki.kotlin-conventions-junit4'
    id 'com.google.devtools.ksp' version("1.9.10-1.0.13")
    id 'com.anaplan.engineering.kazuki-generation'
}

dependencies {
    api project(":kazuki-core")
    ksp project(":kazuki-ksp")
}

// TODO - figure out how to do this from the plugin ?!
sourceSets {
    test {
        kotlin {
            srcDir(generateRecordTests)
        }
    }
}

ksp {
    arg("com.anaplan.engineering.kazuki.compile.debug.level", "INFO")
}

test {
    enableAssertions = true
}