include(
        "kazuki-core",
        "kazuki-core-test",
        "kazuki-ksp",
        "kazuki-syntax-examples",
        "kazuki-toolkit",
        "kazuki-toolkit-examples",
        "examples:abstractpacemaker",
        "examples:alarmv1",
        "examples:alarmv2",
        "examples:gameoflife",
        "examples:tictactoe",
        "examples:usingz",
)
includeBuild("kazuki-generation")
includeBuild("build-conventions")