plugins {
    id 'kazuki.kotlin-conventions'
    id 'kazuki.jar-publishing-conventions'
    id 'com.google.devtools.ksp' version("2.0.21-1.0.27")
}

dependencies {
    api project(":kazuki-core")
    ksp project(":kazuki-ksp")
}

tasks.named('compileKotlin', org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask.class) {
    compilerOptions {
        freeCompilerArgs.add("-Xjvm-default=all")
    }
}

ksp {
    useKsp2 = false
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Kazuki toolkit'
                description = 'Toolkit of generic functions for use with the Kazuki specification framework'
            }
        }
    }
}