plugins {
    id 'kazuki.kotlin-conventions'
    alias(libs.plugins.pluginPublish)
}


dependencies {
    implementation gradleApi()
    implementation libs.kotlinPoet
}

gradlePlugin {
    plugins {
        kazukiGeneration {
            id = "${group}.kazuki-generation"
            implementationClass = "com.anaplan.engineering.kazuki.generation.KazukiGenerationPlugin"
        }
    }
}

