plugins {
    id 'kazuki.kotlin-conventions'
    id 'kazuki.jar-publishing-conventions'
    id 'com.anaplan.engineering.kazuki-generation'
}

dependencies {
    implementation 'org.slf4j:slf4j-api:2.0.16'
}


// TODO - figure out how to do this from the plugin ?!
sourceSets {
    main {
        kotlin {
            srcDir(generateTuples)
            srcDir(generateFunctions)
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Kazuki'
                description = 'The core library of the Kazuki specification framework'
            }
        }
    }
}
