[versions]
kotlin = "2.0.21"
ksp = "2.0.21-1.0.27"
kotlinPoet = "2.2.0" # supports up to Kotlin 2.1.21 and KSP 2.1.21-2.0.1

[libraries]
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }

ksp-symbolProcessingApi = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

kotlinPoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinPoet" }
kotlinPoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinPoet" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.0" }
