plugins {
    id 'kazuki.kotlin-conventions'
    id 'kazuki.jar-publishing-conventions'
}

dependencies {
    implementation project(":kazuki-core")
    implementation libs.ksp.symbolProcessingApi
    implementation libs.kotlinPoet
    implementation libs.kotlinPoet.ksp

    testImplementation libs.kotlin.test.junit
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Kazuki KSP'
                description = 'The KSP to support Kazuki'
            }
        }
    }
}

