plugins {
    id 'kazuki.kotlin-conventions'
    id 'kazuki.jar-publishing-conventions'
}

dependencies {
    implementation project(":kazuki-core")
    implementation 'com.google.devtools.ksp:symbol-processing-api:2.0.21-1.0.27'
    implementation 'com.squareup:kotlinpoet:2.2.0'
    implementation 'com.squareup:kotlinpoet-ksp:2.2.0'

    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Kazuki KSP'
                description = 'The KSP to support Kazuki'
            }
        }
    }
}

